# Generated by Django 3.2.5 on 2021-08-03 08:04

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juggle_challenge.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=juggle_challenge.utils.now_with_tz)),
                ('updated_at', models.DateTimeField(default=juggle_challenge.utils.now_with_tz)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=juggle_challenge.utils.now_with_tz)),
                ('updated_at', models.DateTimeField(default=juggle_challenge.utils.now_with_tz)),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=juggle_challenge.utils.now_with_tz)),
                ('updated_at', models.DateTimeField(default=juggle_challenge.utils.now_with_tz)),
                ('title', models.CharField(max_length=50)),
                ('daily_rate_range', models.DecimalField(decimal_places=3, max_digits=20)),
                ('availability_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('location_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=juggle_challenge.utils.now_with_tz)),
                ('updated_at', models.DateTimeField(default=juggle_challenge.utils.now_with_tz)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(help_text='Email address of the professional', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('title', models.CharField(max_length=50)),
                ('daily_rate_range', models.DecimalField(decimal_places=3, max_digits=20)),
                ('availability_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('location_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('jobs', models.ManyToManyField(blank=True, related_name='professional_list', through='api.Application', to='api.Job')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professional'),
        ),
    ]
